### ISSUE TITLE
systemd-sysupdate requires version 257~devel

### ISSUE THREAD

**Issue by flukeeey** [systemd/particleos#3]
Hi!

Great work on this project, this looks to tick a lot of boxes I have for a modern distro. 

However, I've managed to boot into a particle os install but after adding some packages and files to my config, trying to update using sysupdate as per the README.md yields the error in the issue title. 

Is there a way of downloading a systemd devel toolchain? I'm using ToolsTree=default. 

I'm running Arch btw. 😋

**Comment by DaanDeMeyer** [comment]
@flukeeey Apologies, I just added a section to the readme on how to use this with systemd built from source which is unfortunately a requirement for now. Let me know if the instructions are still unclear or need more clarification.
